apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flask-config
  labels:
    app: flask-app
data:
  DB_HOST: "{{ .Release.Name }}-mysql"
  DB_NAME: "{{ .Values.database.name }}"
  DB_PORT: "{{ .Values.mysql.service.port }}"
  FLASK_ENV: "development"
  PORT: "5000"