apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  labels:
    app: mysql
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.password }}
